/**
 * REFERENCE FINGERPRINT GENERATOR (utility, not a behaviour test).
 *
 * Reads real recordings from ../audio-samples, computes their acoustic
 * fingerprints with the canonical front-end (fingerprintConfig), and writes
 * src/core/ml/referenceFingerprints.ts — the two libraries the discriminative
 * matcher compares against:
 *   - REFERENCE_FINGERPRINTS  : drone clips   (yes_drone + Bebop + Membo)
 *   - BACKGROUND_FINGERPRINTS : non-drone clips (ESC-50 / Speech)
 *
 * Run on demand to (re)generate:  npx jest _buildReferenceFingerprints
 * Skips cleanly when the audio folder is absent (e.g. on CI).
 */

import * as fs from 'fs';
import * as path from 'path';
import { FFTProcessor } from '../src/core/audio/FFTProcessor';
import { MelSpectrogram } from '../src/core/audio/MelSpectrogram';
import { computeFingerprint } from '../src/core/ml/AcousticFingerprint';
import {
  FP_SAMPLE_RATE, FP_FFT_SIZE, FP_HOP, FP_MEL_BINS, FP_FMIN, FP_FMAX,
} from '../src/core/ml/fingerprintConfig';

const AUDIO_ROOT = path.join(__dirname, '..', '..', 'audio-samples');
const OUT_FILE = path.join(__dirname, '..', 'src', 'core', 'ml', 'referenceFingerprints.ts');

const DRONE_PER_SOURCE = 40;   // per drone source dir → 120 drone references
const BACKGROUND_COUNT = 90;   // background references

function decodeWav(buf: Buffer): Float32Array | null {
  if (buf.length < 44 || buf.toString('ascii', 0, 4) !== 'RIFF') return null;
  if (buf.toString('ascii', 8, 12) !== 'WAVE') return null;
  let offset = 12;
  let bits = 16;
  let dataStart = -1;
  let dataLen = 0;
  while (offset + 8 <= buf.length) {
    const id = buf.toString('ascii', offset, offset + 4);
    const size = buf.readUInt32LE(offset + 4);
    if (id === 'fmt ') bits = buf.readUInt16LE(offset + 8 + 14);
    else if (id === 'data') { dataStart = offset + 8; dataLen = size; break; }
    offset += 8 + size + (size % 2);
  }
  if (dataStart < 0 || bits !== 16) return null;
  const end = Math.min(dataStart + dataLen, buf.length);
  const n = Math.floor((end - dataStart) / 2);
  const out = new Float32Array(n);
  for (let i = 0; i < n; i++) out[i] = buf.readInt16LE(dataStart + i * 2) / 32768;
  return out;
}

describe('reference fingerprint generator', () => {
  const haveAudio = fs.existsSync(path.join(AUDIO_ROOT, 'yes_drone'));

  (haveAudio ? it : it.skip)('writes referenceFingerprints.ts from real recordings', () => {
    const fft = new FFTProcessor(FP_FFT_SIZE);
    const mel = new MelSpectrogram(FP_MEL_BINS, FP_FFT_SIZE, FP_SAMPLE_RATE, FP_FMIN, FP_FMAX);

    const fingerprintOf = (file: string): number[] | null => {
      const pcm = decodeWav(fs.readFileSync(file));
      if (!pcm || pcm.length < FP_FFT_SIZE) return null;
      const frames: Float32Array[] = [];
      for (let s = 0; s + FP_FFT_SIZE <= pcm.length; s += FP_HOP) {
        frames.push(mel.computeMelFrame(fft.computeMagnitudeSpectrum(pcm.subarray(s, s + FP_FFT_SIZE))));
      }
      const fp = frames.length > 0 ? computeFingerprint(frames) : null;
      return fp ? fp.vector.map((v) => Math.round(v * 1e5) / 1e5) : null;
    };

    // Generate a spread of fingerprint entries from one directory.
    const generate = (dir: string, label: string, count: number): string[] => {
      const full = path.join(AUDIO_ROOT, dir);
      if (!fs.existsSync(full)) return [];
      const files = fs.readdirSync(full).filter((f) => f.toLowerCase().endsWith('.wav')).sort();
      const step = Math.max(1, Math.floor(files.length / count));
      const entries: string[] = [];
      for (let i = 0, picked = 0; i < files.length && picked < count; i += step, picked++) {
        const vec = fingerprintOf(path.join(full, files[i]));
        if (!vec) continue;
        entries.push(
          `  { label: ${JSON.stringify(label)}, sourceId: ${JSON.stringify(`${dir}/${files[i]}`)}, vector: [${vec.join(',')}] },`,
        );
      }
      return entries;
    };

    const droneEntries = [
      ...generate('yes_drone', 'MULTIROTOR', DRONE_PER_SOURCE),
      ...generate('bebop', 'MULTIROTOR', DRONE_PER_SOURCE),
      ...generate('membo', 'MULTIROTOR', DRONE_PER_SOURCE),
    ];
    const backgroundEntries = generate('unknown', 'BACKGROUND', BACKGROUND_COUNT);

    const content = `/**
 * Reference fingerprint libraries — AUTO-GENERATED, do not edit by hand.
 *
 * Generated by __tests__/_buildReferenceFingerprints.test.ts from real
 * recordings (DroneAudioDataset — Sara Al-Emadi). Each entry is the
 * mean-subtracted, L2-normalised average log-mel fingerprint of one clip,
 * computed with the canonical spec in fingerprintConfig.ts.
 *
 * The discriminative matcher compares incoming audio against BOTH libraries.
 *   REFERENCE_FINGERPRINTS  — ${droneEntries.length} drone clips
 *   BACKGROUND_FINGERPRINTS — ${backgroundEntries.length} non-drone clips
 *
 * Regenerate with:  npx jest _buildReferenceFingerprints
 */

import type { ReferenceFingerprint } from './AcousticFingerprint';

export const REFERENCE_FINGERPRINTS: ReferenceFingerprint[] = [
${droneEntries.join('\n')}
];

export const BACKGROUND_FINGERPRINTS: ReferenceFingerprint[] = [
${backgroundEntries.join('\n')}
];
`;

    fs.writeFileSync(OUT_FILE, content, 'utf8');
    // eslint-disable-next-line no-console
    console.log(`[buildReferenceFingerprints] wrote ${droneEntries.length} drone + ` +
      `${backgroundEntries.length} background fingerprints → ${OUT_FILE}`);

    expect(droneEntries.length).toBeGreaterThan(0);
    expect(backgroundEntries.length).toBeGreaterThan(0);
  }, 180000);
});
